spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com/
          predicates:
            - Query=url,qq

        #将路径为path=/api/**转发至 mall-product
        - id: product_route
#          uri: lb://mall-product:12000
          uri: http://localhost:12000
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}


        #将路径为path=/api/**转发至 mall-member
        - id: member_route
#                    uri: lb://mall-product
          uri: http://localhost:8000
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}


        #将路径为Path=/api/**转发至后台管理
        - id: admin_route
#          uri: lb://renren-fast:8080
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}






server:
  port: 88

 #nacos服务名和地址







