spring:
  datasource:
    url: jdbc:mysql://47.107.108.206:3306/mall-ware?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
    hikari:
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-lifetime: 900000


  application:
    name: mall-ware

  profiles:
    active: nacos

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


##mybatis-plus相关配置
mybatis-plus:
  mapper-locations: mapper/**/*.xml
  #主键自增
  global-config:
    db-config:
      id-type: auto


#配置端口号
server:
  port: 11000

logging:
  level:
    com.hwj.mall: debug
