server:
  port: 30000

spring:
  application:
    name: mall-cart
  profiles:
    active: nacos,redis,sentinel
  session:
    store-type: redis

#防止调用feign接口超时
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 300000


# 自定义线程池参数
mall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
