spring:
  datasource:
    url: jdbc:mysql://47.107.108.206:3306/mall-product?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root  #用户名
    password: 123456  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
    hikari:
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-lifetime: 900000

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: mall-product

  profiles:
    active: nacos

  thymeleaf:
    cache: false
#    suffix: .html
#    prefix: classpath:/templates/

  redis:
    host: 47.107.108.206
    port: 6379

  session:
    store-type: redis

#防止调用feign接口超时
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 300000


##mybatis-plus相关配置
mybatis-plus:
  mapper-locations: mapper/**/*.xml
  #主键自增
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delete_flag
      logic-delete-value: 1 #逻辑已删除的值
      logic-not-delete-value: 0 #逻辑为删除的值
logging:
  level:
    com.hwj.mall: debug


#配置端口号
server:
  port: 12000
