spring:
  rabbitmq:
    host: 47.107.108.206
    port: 5672
    #    虚拟主机
    virtual-host: /

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: mall-seckill

  profiles:
    active: nacos,redis,sentinel

  thymeleaf:
    cache: false
#    suffix: .html
#    prefix: classpath:/templates/

#配置端口号
server:
  port: 14000


#防止调用feign接口超时
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 300000

logging:
  level:
    com.hwj.mall: debug




