spring:
  application:
    name: mall-search

  profiles:
    active: nacos,redis,sentinel,zipkin

  thymeleaf:
    cache: false
  #    suffix: .html
  #    prefix: classpath:/templates/

  session:
    store-type: redis

#配置端口号
server:
  port: 13000