spring:
  application:
    name: mall-auth-server

  profiles:
    active: nacos,redis

  thymeleaf:
    cache: false

  session:
    store-type: redis
    timeout: 100m


#配置端口号
server:
  port: 20000