spring:
  application:
    name: mall-auth-server

  profiles:
    active: nacos,redis,sentinel

  thymeleaf:
    cache: false

  session:
    store-type: redis
    timeout: 100m


#配置端口号
server:
  port: 20000

#防止调用feign接口超时
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 300000